source      'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!

inhibit_all_warnings!
target :RefreshController  do

    pod 'ATKit_ObjectC'
    pod 'Masonry'
    pod 'DZNEmptyDataSet'
    pod 'KVOController'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'YYModel'
    pod 'SDWebImage'
    pod 'ATRefresh_ObjectC',:git => 'https://github.com/tianya2416/ATRefresh_ObjectC.git'
end
