#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

inhibit_all_warnings!
target :RefreshController  do
    pod 'AppBaseCategory'
    pod 'Masonry'
    pod 'DZNEmptyDataSet'
    pod 'YYKit'
    pod 'KVOController'
    pod 'AFNetworking'
    pod 'MJRefresh', :git => 'https://github.com/CoderLT/MJRefresh.git'
end
